---
title: "Buyuk Veri ve Veri Tabanlari ile Calismak"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

# 1. Veri Tabanlari ile Calisma

## 1.1 Veri Tabanina Baglanma

```{r}

#MS-SQL SERVER Veri Tabanina Baglanma - 1.Yol

library(RODBC)
library(DBI)
library(odbc)
library(ggplot2)


con <- DBI::dbConnect(odbc::odbc(),
                        Driver = "SQL Server",
                        Server = "LAPTOP-4C7DUVGM",
                        Database = "Northwind",
                        trusted_connection = "yes",
                        port = "1433"
                      )

# Veri Okuma

df <- DBI::dbReadTable(con,"Customers")
df <- DBI::dbGetQuery(con,"Select Country, count(*) as Ulke_Sayisi from Customers group by Country " )
df

# Gorsellestirme
pl <- ggplot(data = df, aes( x = Country, y = Ulke_Sayisi)) +
  geom_bar(stat = "identity")

pl


# Veri Tabanina Kaydetme
DBI:: dbWriteTable(con,"Ulke_Sayilari", df)

# Veri Tabanindan Silme
DBI:: dbRemoveTable(con,"Ulke_Sayilari")

# Var Olan Tabloya Ekleme Yapma
DBI::dbAppendTable(con, "Ulke_Sayilari", df)
dfAppended <- DBI::dbReadTable(con,"Ulke_Sayilari")


```


```{r}

#MS-SQL SERVER Veri Tabanina Baglanma - 2.Yol

library(RODBC)
library(DBI)
library(odbc)

con2 <- odbcConnect("SQLServer_DSN")

# Veri Okuma
sqlQuery(con2,"SELECT * FROM Customers")

```

# 1.2 dplyr ile Sorgu
```{r}

# dplyr kütüphanesi ile Sorgu Göndermek

library(dplyr)

# Veri seti icerisinde Customer tablosuna erisim saglayip bir atama ile kaydettik.

db <- tbl(con,"Products")

db %>% group_by(ProductName) %>%
  summarise(ortalama = mean(UnitPrice))

```


# 1.3 Sorguyu SQL' e Cevirme

```{r}

# dplyr'e kodunu SQL koduna cevirme islemi yaparken kod kisminin arkasina pipe operatoru ile show_query() fonksiyonunu yaziyoruz.

db %>% group_by(ProductName) %>%
  summarise(ortalama = mean(UnitPrice)) %>% show_query()

```

# Buyuk Veri ile Calismak (Spark)

Amacımız, Spark ortamindaki tablolara erismek ve analiz etme islemidir.

```{r}

library(dplyr)

# R ile Spark arasindaki baglantiyi kurmak icin gerekli olan kutuphane
install.packages("sparklyr")
library(sparklyr)

# kullanacagimiz olan veri seti
library(nycflights13)

# spark'a baglanti
sc <- spark_connect(master = "local")


# R icerisindeki local bir dataframe'i baglanti uzerindeki sunucuya aktarma
copy_to(sc, nycflights13::flights, "flights_spark")

# Spark icerisindeki verileri gormek icin
src_tbls(sc)


# ANALIZ ETME

f_tbl <- copy_to(sc, nycflights13::flights, "flights_spark", overwrite = TRUE)

f_tbl %>% select(1:3)  # ilk 3 degiskeni alma

# Havayolu sirketlerine gore gecikme surelerinin ortalaması

f_tbl %>% group_by(carrier) %>%
  summarise(ucus_sayisi = n(), ort_gecikme = mean(dep_delay))

# GORSELLESTIRME

library(ggplot2)

# collect() fonksiyonu ile veriyi toplulasirma yaparak kendi R icerimize kaydediyoruz.

df <- f_tbl %>% group_by(carrier) %>%
  summarise(ucus_sayisi = n(), ort_gecikme = mean(dep_delay)) %>% collect()

ggplot(df, aes(x = carrier, y = ort_gecikme)) + 
  geom_bar(stat = "identity")

```


